version: '3.7'

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passroot
      MONGO_INITDB_DATABASE: calendar-api
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb_container
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: passroot

#  app:
#    container_name: app
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: base
#    command: sh -c "npm install & npm start"
#    ports:
#      - '5555:5555'
#    working_dir: /app
#    volumes:
#      - ./:/app

volumes:
  mongodb_data_container:

